package sqlparser

var AllowedFunctions map[string]struct{}

func init() {
	AllowedFunctions = map[string]struct{}{
		// core functions
		"abs": {},
		// "changes":                   {},
		"char":     {},
		"coalesce": {},
		"format":   {},
		"glob":     {},
		"hex":      {},
		"ifnull":   {},
		"iif":      {},
		"instr":    {},
		//"last_insert_rowid":         {},
		"length": {},
		"like":   {},
		//"likelihood":                {},
		//	"likely":                    {},
		//"load_extension":            {},
		"lower":  {},
		"ltrim":  {},
		"max":    {},
		"min":    {},
		"nullif": {},
		"printf": {},
		"quote":  {},
		//"random":                    {},
		//"randomblob":                {},
		"replace": {},
		"round":   {},
		"rtrim":   {},
		"sign":    {},
		//"soundex":                   {},
		//"sqlite_compileoption_get":  {},
		//"sqlite_compileoption_used": {},
		//"sqlite_offset":             {},
		//"sqlite_source_id":          {},
		//"sqlite_version":            {},
		"substr":    {},
		"substring": {},
		//"total_changes": {},
		"trim":    {},
		"typeof":  {},
		"unicode": {},
		//"unlikely": {},
		"upper": {},
		//"zeroblob": {},

		// math functions
		"acos":    {},
		"acosh":   {},
		"asin":    {},
		"asinh":   {},
		"atan":    {},
		"atan2":   {},
		"atanh":   {},
		"ceil":    {},
		"ceiling": {},
		"cos":     {},
		"cosh":    {},
		"degrees": {},
		"exp":     {},
		"floor":   {},
		"ln":      {},
		"log":     {},
		"log10":   {},
		"log2":    {},
		"mod":     {},
		"pi":      {},
		"pow":     {},
		"power":   {},
		"radians": {},
		"sin":     {},
		"sinh":    {},
		"sqrt":    {},
		"tan":     {},
		"tanh":    {},
		"trunc":   {},

		// date & time functions
		"date":      {},
		"time":      {},
		"datetime":  {},
		"julianday": {},
		"unixepoch": {},
		"strftime":  {},

		// json functions
		"json":              {},
		"json_array":        {},
		"json_array_length": {},
		"json_extract":      {},
		"json_insert":       {},
		"json_object":       {},
		"json_patch":        {},
		"json_remove":       {},
		"json_replace":      {},
		"json_set":          {},
		"json_type":         {},
		"json_valid":        {},
		"json_quote":        {},
		"json_group_array":  {},
		"json_group_object": {},

		// aggregate functions
		"avg":          {},
		"count":        {},
		"group_concat": {},
		// "max":          {},
		// "min":          {},
		"sum":   {},
		"total": {},
	}
}
