// Code generated by goyacc -l -o yy_parser.go grammar.y. DO NOT EDIT.
package sqlparser

import __yyfmt__ "fmt"

const MaxColumnNameLength = 64

type yySymType struct {
	yys              int
	bool             bool
	string           string
	bytes            []byte
	expr             Expr
	exprs            Exprs
	column           *Column
	table            *Table
	convertType      ConvertType
	when             *When
	whens            []*When
	SelectColumn     SelectColumn
	SelectColumnList SelectColumnList
	selectStmt       *Select
	where            *Where
	limit            *Limit
	orderBy          OrderBy
	orderingTerm     *OrderingTerm
	nulls            NullsType
	tableExprList    TableExprList
	tableExpr        TableExpr
	joinTableExpr    *JoinTableExpr
	columnList       ColumnList
	subquery         *Subquery
	colTuple         ColTuple
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGRAL = 57348
const HEXNUM = 57349
const FLOAT = 57350
const BLOB = 57351
const ERROR = 57352
const TRUE = 57353
const FALSE = 57354
const NULL = 57355
const AND = 57356
const NONE = 57357
const INTEGER = 57358
const NUMERIC = 57359
const REAL = 57360
const TEXT = 57361
const CAST = 57362
const AS = 57363
const CASE = 57364
const WHEN = 57365
const THEN = 57366
const ELSE = 57367
const END = 57368
const SELECT = 57369
const FROM = 57370
const WHERE = 57371
const GROUP = 57372
const BY = 57373
const HAVING = 57374
const LIMIT = 57375
const OFFSET = 57376
const ORDER = 57377
const ASC = 57378
const DESC = 57379
const NULLS = 57380
const FIRST = 57381
const LAST = 57382
const DISTINCT = 57383
const ALL = 57384
const EXISTS = 57385
const FILTER = 57386
const JOIN = 57387
const ON = 57388
const USING = 57389
const OR = 57390
const ANDOP = 57391
const NOT = 57392
const IS = 57393
const ISNOT = 57394
const MATCH = 57395
const GLOB = 57396
const REGEXP = 57397
const LIKE = 57398
const BETWEEN = 57399
const IN = 57400
const ISNULL = 57401
const NOTNULL = 57402
const NE = 57403
const LE = 57404
const GE = 57405
const INEQUALITY = 57406
const ESCAPE = 57407
const LSHIFT = 57408
const RSHIFT = 57409
const CONCAT = 57410
const JSON_EXTRACT_OP = 57411
const JSON_UNQUOTE_EXTRACT_OP = 57412
const COLLATE = 57413
const UNARY = 57414

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGRAL",
	"HEXNUM",
	"FLOAT",
	"BLOB",
	"ERROR",
	"TRUE",
	"FALSE",
	"NULL",
	"AND",
	"'('",
	"','",
	"')'",
	"'.'",
	"NONE",
	"INTEGER",
	"NUMERIC",
	"REAL",
	"TEXT",
	"CAST",
	"AS",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP",
	"BY",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"ORDER",
	"ASC",
	"DESC",
	"NULLS",
	"FIRST",
	"LAST",
	"DISTINCT",
	"ALL",
	"EXISTS",
	"FILTER",
	"JOIN",
	"ON",
	"USING",
	"OR",
	"ANDOP",
	"NOT",
	"IS",
	"ISNOT",
	"MATCH",
	"GLOB",
	"REGEXP",
	"LIKE",
	"BETWEEN",
	"IN",
	"ISNULL",
	"NOTNULL",
	"NE",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"INEQUALITY",
	"ESCAPE",
	"'&'",
	"'|'",
	"LSHIFT",
	"RSHIFT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"CONCAT",
	"JSON_EXTRACT_OP",
	"JSON_UNQUOTE_EXTRACT_OP",
	"COLLATE",
	"'~'",
	"UNARY",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 24,
	18, 55,
	-2, 104,
}

const yyPrivate = 57344

const yyLast = 1025

var yyAct = [...]int16{
	89, 238, 13, 209, 161, 10, 87, 217, 162, 143,
	134, 88, 2, 63, 140, 81, 83, 84, 86, 101,
	160, 82, 100, 65, 218, 219, 11, 159, 19, 210,
	102, 43, 44, 45, 50, 51, 52, 63, 94, 10,
	5, 6, 106, 107, 108, 109, 110, 111, 112, 113,
	114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
	11, 103, 92, 132, 72, 73, 74, 75, 257, 169,
	46, 47, 48, 49, 41, 42, 43, 44, 45, 50,
	51, 52, 63, 139, 50, 51, 52, 63, 151, 138,
	137, 148, 214, 136, 259, 260, 153, 154, 230, 157,
	41, 42, 43, 44, 45, 50, 51, 52, 63, 195,
	24, 25, 26, 29, 27, 28, 166, 30, 31, 32,
	8, 18, 150, 152, 168, 170, 103, 167, 156, 187,
	21, 231, 17, 188, 234, 98, 3, 171, 105, 199,
	144, 159, 174, 141, 139, 178, 144, 179, 177, 104,
	80, 38, 176, 33, 223, 136, 182, 251, 250, 99,
	34, 208, 124, 193, 35, 3, 36, 39, 183, 125,
	196, 147, 192, 197, 246, 164, 165, 146, 200, 158,
	103, 103, 103, 15, 14, 211, 212, 233, 215, 189,
	190, 191, 16, 146, 198, 216, 163, 225, 221, 220,
	158, 194, 222, 146, 145, 135, 93, 78, 79, 96,
	95, 91, 224, 129, 128, 127, 130, 131, 126, 232,
	203, 206, 207, 205, 204, 90, 105, 140, 66, 235,
	133, 236, 239, 164, 165, 242, 241, 104, 78, 79,
	1, 149, 240, 37, 256, 253, 254, 239, 255, 237,
	213, 229, 142, 202, 258, 57, 56, 61, 58, 186,
	71, 70, 69, 76, 77, 64, 59, 60, 68, 67,
	72, 73, 74, 75, 97, 7, 46, 47, 48, 49,
	41, 42, 43, 44, 45, 50, 51, 52, 63, 248,
	249, 40, 4, 247, 62, 55, 54, 53, 155, 244,
	181, 57, 56, 61, 58, 20, 71, 70, 69, 76,
	77, 64, 59, 60, 68, 67, 72, 73, 74, 75,
	175, 245, 46, 47, 48, 49, 41, 42, 43, 44,
	45, 50, 51, 52, 63, 57, 56, 61, 58, 85,
	71, 70, 69, 76, 77, 64, 59, 60, 68, 67,
	72, 73, 74, 75, 228, 227, 46, 47, 48, 49,
	41, 42, 43, 44, 45, 50, 51, 52, 63, 72,
	73, 74, 75, 23, 22, 46, 47, 48, 49, 41,
	42, 43, 44, 45, 50, 51, 52, 63, 12, 252,
	57, 56, 61, 58, 0, 71, 70, 69, 76, 77,
	64, 59, 60, 68, 67, 72, 73, 74, 75, 0,
	0, 46, 47, 48, 49, 41, 42, 43, 44, 45,
	50, 51, 52, 63, 57, 56, 61, 58, 243, 71,
	70, 69, 76, 77, 64, 59, 60, 68, 67, 72,
	73, 74, 75, 0, 0, 46, 47, 48, 49, 41,
	42, 43, 44, 45, 50, 51, 52, 63, 0, 0,
	0, 0, 226, 57, 56, 61, 58, 0, 71, 70,
	69, 76, 77, 64, 59, 60, 68, 67, 72, 73,
	74, 75, 0, 0, 46, 47, 48, 49, 41, 42,
	43, 44, 45, 50, 51, 52, 63, 57, 56, 61,
	58, 0, 71, 70, 69, 76, 77, 64, 59, 60,
	68, 67, 72, 73, 74, 75, 201, 0, 46, 47,
	48, 49, 41, 42, 43, 44, 45, 50, 51, 52,
	63, 0, 0, 0, 0, 0, 0, 0, 185, 0,
	57, 56, 61, 58, 0, 71, 70, 69, 76, 77,
	64, 59, 60, 68, 67, 72, 73, 74, 75, 0,
	0, 46, 47, 48, 49, 41, 42, 43, 44, 45,
	50, 51, 52, 63, 57, 56, 61, 58, 184, 71,
	70, 69, 76, 77, 64, 59, 60, 68, 67, 72,
	73, 74, 75, 0, 0, 46, 47, 48, 49, 41,
	42, 43, 44, 45, 50, 51, 52, 63, 0, 0,
	0, 0, 0, 0, 57, 56, 61, 58, 0, 71,
	70, 69, 76, 77, 64, 59, 60, 68, 67, 72,
	73, 74, 75, 180, 0, 46, 47, 48, 49, 41,
	42, 43, 44, 45, 50, 51, 52, 63, 0, 0,
	0, 0, 0, 0, 0, 0, 172, 0, 0, 0,
	57, 56, 61, 58, 0, 71, 70, 69, 76, 77,
	64, 59, 60, 68, 67, 72, 73, 74, 75, 0,
	0, 46, 47, 48, 49, 41, 42, 43, 44, 45,
	50, 51, 52, 63, 57, 56, 61, 58, 0, 71,
	70, 69, 76, 77, 64, 59, 60, 68, 67, 72,
	73, 74, 75, 0, 0, 46, 47, 48, 49, 41,
	42, 43, 44, 45, 50, 51, 52, 63, 57, 56,
	61, 58, 0, 71, 70, 69, 76, 77, 64, 59,
	60, 68, 67, 72, 73, 74, 75, 0, 0, 46,
	47, 48, 49, 41, 42, 43, 44, 45, 50, 51,
	52, 63, 56, 61, 58, 0, 71, 70, 69, 76,
	77, 64, 59, 60, 68, 67, 72, 73, 74, 75,
	0, 0, 46, 47, 48, 49, 41, 42, 43, 44,
	45, 50, 51, 52, 63, 61, 58, 0, 71, 70,
	69, 76, 77, 64, 59, 60, 68, 67, 72, 73,
	74, 75, 0, 0, 46, 47, 48, 49, 41, 42,
	43, 44, 45, 50, 51, 52, 63, 24, 25, 26,
	29, 27, 28, 0, 30, 31, 32, 0, 18, 0,
	173, 0, 0, 0, 0, 0, 0, 21, 0, 17,
	0, 0, 0, 0, 3, 0, 24, 25, 26, 29,
	27, 28, 0, 30, 31, 32, 0, 18, 0, 0,
	33, 0, 0, 0, 0, 0, 21, 34, 17, 0,
	0, 35, 0, 36, 46, 47, 48, 49, 41, 42,
	43, 44, 45, 50, 51, 52, 63, 0, 0, 33,
	15, 14, 0, 0, 0, 0, 34, 0, 0, 16,
	35, 0, 36, 24, 25, 26, 29, 27, 28, 0,
	30, 31, 32, 0, 18, 0, 0, 0, 0, 15,
	14, 9, 0, 21, 0, 17, 0, 0, 16, 0,
	3, 0, 24, 25, 26, 29, 27, 28, 0, 30,
	31, 32, 0, 18, 0, 0, 33, 0, 0, 0,
	0, 0, 21, 34, 17, 0, 0, 35, 0, 36,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 33, 15, 14, 0, 0,
	0, 0, 34, 0, 0, 16, 35, 0, 36, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 15, 14, 0, 0, 0,
	0, 0, 0, 0, 16,
}

var yyPact = [...]int16{
	105, -1000, -1000, -5, 852, -1000, -1000, 135, -1000, -1000,
	203, 132, -1000, -1000, 938, 938, 938, 938, 909, -1000,
	-1000, 210, -1000, -1000, 196, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 191, -9, 195, 194, 102, 852, 222,
	-1000, 938, 938, 938, 938, 938, 938, 938, 938, 938,
	938, 938, 938, 938, 938, 938, 938, 938, 106, -1000,
	-1000, 156, 938, 226, 190, -1000, 234, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	10, -1000, 125, -1000, -1000, 113, 676, 187, 154, 676,
	938, 43, -1000, 105, 191, 938, 938, 94, 938, -1000,
	163, -22, -29, 171, 134, -1000, -48, -48, 2, 2,
	2, 23, 23, 23, 23, -72, -72, -72, 302, 811,
	-3, 741, 709, 302, 938, -1000, 190, -1000, -1000, -1000,
	-1000, -1000, 642, -1000, -1000, 823, -1000, -1000, -1000, -1000,
	-1000, 223, 119, -1000, 938, -1000, 938, -1000, 608, 938,
	151, -1000, -1000, 562, 522, 93, 98, 676, 222, 222,
	222, -1000, -1000, 229, -1000, -1000, 146, 184, 92, 938,
	302, -1000, 938, -1000, 177, 109, -1000, 938, 488, 676,
	201, 144, 161, -19, 938, 938, 53, 938, 938, -1000,
	-26, -26, -1000, 171, -1000, -1000, 302, 302, -1000, -1000,
	676, 938, 137, -1000, -1000, -1000, -1000, -1000, -19, -1000,
	182, 445, 338, 61, 96, 676, 161, -1000, 938, 172,
	-1000, -1000, 676, -1000, -1000, 101, -1000, -1000, 938, -1000,
	938, 938, 676, 223, 938, 411, 283, 158, -1000, 249,
	141, -1000, 372, -1000, 938, 938, 938, 26, -1000, -1000,
	-1000, 223, -1000, 676, 676, -1000, -1000, 51, -1000, -1000,
	-1000,
}

var yyPgo = [...]int16{
	0, 11, 0, 388, 374, 373, 339, 320, 305, 6,
	300, 298, 297, 296, 295, 294, 293, 292, 2, 291,
	23, 120, 275, 21, 4, 8, 274, 259, 3, 253,
	9, 252, 251, 250, 249, 1, 244, 22, 243, 30,
	19, 7, 242, 28, 10, 241, 240,
}

var yyR1 = [...]int8{
	0, 46, 1, 17, 17, 17, 22, 22, 21, 21,
	21, 19, 19, 19, 20, 20, 38, 38, 37, 37,
	39, 39, 39, 39, 24, 24, 24, 25, 25, 40,
	40, 41, 41, 41, 26, 26, 11, 11, 27, 27,
	33, 33, 34, 34, 35, 16, 16, 16, 36, 36,
	36, 32, 32, 32, 32, 23, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
	3, 3, 3, 3, 18, 42, 42, 12, 12, 12,
	12, 12, 12, 12, 12, 13, 13, 13, 13, 14,
	14, 15, 15, 29, 29, 29, 29, 29, 44, 44,
	44, 43, 8, 8, 4, 4, 4, 5, 5, 45,
	45, 9, 9, 10, 10, 28, 28, 6, 6, 30,
	31, 31, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 9, 0, 1, 1, 1, 3, 1, 2,
	3, 0, 1, 2, 1, 1, 2, 2, 1, 3,
	2, 4, 3, 3, 0, 1, 2, 1, 1, 4,
	4, 0, 2, 4, 0, 2, 0, 3, 0, 2,
	0, 3, 1, 3, 3, 0, 1, 1, 0, 2,
	2, 0, 2, 4, 4, 1, 1, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 5, 2, 2, 2, 3, 3,
	3, 4, 2, 2, 3, 5, 5, 3, 3, 3,
	4, 1, 1, 6, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
	2, 1, 2, 1, 2, 1, 1, 1, 1, 1,
	2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
	3, 3, 2, 3, 6, 6, 8, 6, 5, 0,
	1, 1, 3, 0, 1, 0, 5, 0, 1, 4,
	1, 2, 0, 2,
}

var yyChk = [...]int16{
	-1000, -46, -1, 31, -17, 45, 46, -22, -21, 79,
	-2, -23, -3, -18, 78, 77, 86, 26, 15, -43,
	-8, 24, -4, -5, 4, 5, 6, 8, 9, 7,
	11, 12, 13, 47, 54, 58, 60, -38, 16, 32,
	-19, 77, 78, 79, 80, 81, 73, 74, 75, 76,
	82, 83, 84, -12, -13, -14, 53, 52, 55, 63,
	64, 54, -15, 85, 62, -20, 25, 66, 65, 59,
	58, 57, 67, 68, 69, 70, 60, 61, 4, 5,
	18, -2, -23, -2, -2, -6, -2, -9, -1, -2,
	15, 15, -43, 15, 47, 15, 15, -26, 33, -21,
	-37, -40, -39, -23, 15, 4, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, 56, 13, 62, 59, 58, 57,
	60, 61, -2, 4, -44, 15, -43, -20, 79, -18,
	4, 18, -31, -30, 27, 17, 16, 17, -2, -45,
	79, 45, -43, -2, -2, -11, 34, -2, 16, 49,
	49, -24, -25, 25, 4, 5, -1, -37, -40, 72,
	-2, -44, 14, 17, -9, -7, -30, 29, -2, -2,
	25, -10, -9, 17, 16, 16, -27, 36, 35, -39,
	-39, -39, -25, 17, 17, 17, -2, -2, 17, 30,
	-2, 28, -29, 19, 23, 22, 20, 21, 17, -28,
	48, -2, -2, -33, 39, -2, -9, -41, 50, 51,
	-41, -24, -2, 17, -28, 15, 17, 17, 16, -32,
	37, 35, -2, 15, 33, -2, -2, -34, -35, -2,
	-42, -18, -2, 17, 16, 38, 16, -16, 40, 41,
	17, 16, 17, -2, -2, -35, -36, 42, -18, 43,
	44,
}

var yyDef = [...]int16{
	0, -2, 1, 3, 0, 4, 5, 0, 6, 8,
	11, 0, 56, 57, 0, 0, 0, 147, 0, 91,
	92, 0, 94, 95, -2, 96, 97, 98, 99, 100,
	101, 102, 103, 0, 0, 0, 0, 34, 0, 0,
	9, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 82,
	83, 0, 0, 0, 0, 12, 0, 107, 108, 109,
	111, 113, 115, 116, 117, 118, 119, 121, 14, 15,
	0, 75, 0, 76, 77, 0, 148, 0, 0, 141,
	0, 139, 132, 0, 0, 0, 0, 36, 0, 7,
	16, 17, 18, 24, 0, 55, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 78, 79, 80, 0, 84, 0, 110, 112, 114,
	120, 122, 0, 87, 89, 0, 129, 13, 10, 58,
	104, 0, 152, 150, 0, 88, 0, 131, 0, 143,
	0, 140, 133, 0, 0, 38, 0, 35, 0, 0,
	0, 20, 25, 0, 27, 28, 0, 0, 0, 0,
	81, 90, 0, 128, 0, 0, 151, 0, 0, 142,
	0, 0, 144, 145, 0, 0, 40, 0, 0, 19,
	31, 31, 26, 24, 22, 23, 74, 85, 130, 86,
	153, 0, 0, 123, 124, 125, 126, 127, 145, 138,
	0, 0, 0, 51, 0, 39, 37, 30, 0, 0,
	29, 21, 149, 93, 137, 0, 134, 135, 0, 2,
	0, 0, 32, 0, 0, 0, 52, 41, 42, 45,
	0, 105, 0, 136, 0, 0, 0, 48, 46, 47,
	33, 0, 146, 53, 54, 43, 44, 0, 106, 49,
	50,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 81, 73, 3,
	15, 17, 79, 77, 16, 78, 18, 80, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	67, 66, 68, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 74, 3, 86,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
	46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
	56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
	69, 70, 71, 72, 75, 76, 82, 83, 84, 85,
	87,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).ast = &AST{yyDollar[1].selectStmt}
		}
	case 2:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.selectStmt = &Select{
				Distinct:         yyDollar[2].string,
				SelectColumnList: yyDollar[3].SelectColumnList,
				From:             yyDollar[4].tableExprList,
				Where:            yyDollar[5].where,
				GroupBy:          GroupBy(yyDollar[6].exprs),
				Having:           yyDollar[7].where,
				OrderBy:          yyDollar[8].orderBy,
				Limit:            yyDollar[9].limit,
			}
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = ""
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = DistinctStr
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = AllStr
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.SelectColumnList = SelectColumnList{yyDollar[1].SelectColumn}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.SelectColumnList = append(yyDollar[1].SelectColumnList, yyDollar[3].SelectColumn)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.SelectColumn = &StarSelectColumn{}
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.SelectColumn = &AliasedSelectColumn{Expr: yyDollar[1].expr, As: yyDollar[2].column}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.SelectColumn = &StarSelectColumn{TableRef: yyDollar[1].table}
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.column = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.column = yyDollar[1].column
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.column = yyDollar[2].column
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.column = &Column{Name: string(yyDollar[1].bytes)}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.column = &Column{Name: string(yyDollar[1].bytes)}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExprList = yyDollar[2].tableExprList
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExprList = TableExprList{yyDollar[2].joinTableExpr}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableExprList = TableExprList{yyDollar[1].tableExpr}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExprList = append(yyVAL.tableExprList, yyDollar[3].tableExpr)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: yyDollar[1].table, As: yyDollar[2].table}
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: &Subquery{Select: yyDollar[2].selectStmt}, As: yyDollar[4].table}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExpr = &ParenTableExpr{TableExprList: yyDollar[2].tableExprList}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[2].joinTableExpr
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.table = nil
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.table = yyDollar[1].table
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.table = yyDollar[2].table
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.table = &Table{Name: string(yyDollar[1].bytes)}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.table = &Table{Name: string(yyDollar[1].bytes)}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].joinTableExpr == nil {
				yyVAL.joinTableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, JoinOperator: JoinStr, RightExpr: yyDollar[3].tableExpr}
			} else {
				yyDollar[4].joinTableExpr.LeftExpr = yyDollar[1].tableExpr
				yyDollar[4].joinTableExpr.JoinOperator = JoinStr
				yyDollar[4].joinTableExpr.RightExpr = yyDollar[3].tableExpr
				yyVAL.joinTableExpr = yyDollar[4].joinTableExpr
			}
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].joinTableExpr == nil {
				yyVAL.joinTableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].joinTableExpr, JoinOperator: JoinStr, RightExpr: yyDollar[3].tableExpr}
			} else {
				yyDollar[4].joinTableExpr.LeftExpr = yyDollar[1].joinTableExpr
				yyDollar[4].joinTableExpr.JoinOperator = JoinStr
				yyDollar[4].joinTableExpr.RightExpr = yyDollar[3].tableExpr
				yyVAL.joinTableExpr = yyDollar[4].joinTableExpr
			}
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.joinTableExpr = nil
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.joinTableExpr = &JoinTableExpr{On: yyDollar[2].expr}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.joinTableExpr = &JoinTableExpr{Using: yyDollar[3].columnList}
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.where = NewWhere(WhereStr, yyDollar[2].expr)
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.exprs = nil
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.exprs = yyDollar[3].exprs
		}
	case 38:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.where = NewWhere(HavingStr, yyDollar[2].expr)
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.orderBy = nil
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderBy = yyDollar[3].orderBy
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.orderBy = OrderBy{yyDollar[1].orderingTerm}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderBy = append(yyDollar[1].orderBy, yyDollar[3].orderingTerm)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderingTerm = &OrderingTerm{Expr: yyDollar[1].expr, Direction: yyDollar[2].string, Nulls: yyDollar[3].nulls}
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = AscStr
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = AscStr
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = DescStr
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nulls = NullsNil
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nulls = NullsFirst
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nulls = NullsLast
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.limit = nil
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.limit = &Limit{Limit: yyDollar[2].expr}
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.limit = &Limit{Offset: yyDollar[2].expr, Limit: yyDollar[4].expr}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.limit = &Limit{Offset: yyDollar[4].expr, Limit: yyDollar[2].expr}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.table = &Table{Name: string(yyDollar[1].bytes)}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].column
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[3].column.TableRef = yyDollar[1].table
			yyVAL.expr = yyDollar[3].column
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: PlusStr, Right: yyDollar[3].expr}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: MinusStr, Right: yyDollar[3].expr}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: MultStr, Right: yyDollar[3].expr}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: DivStr, Right: yyDollar[3].expr}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ModStr, Right: yyDollar[3].expr}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: BitAndStr, Right: yyDollar[3].expr}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: BitOrStr, Right: yyDollar[3].expr}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ShiftLeftStr, Right: yyDollar[3].expr}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ShiftRightStr, Right: yyDollar[3].expr}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ConcatStr, Right: yyDollar[3].expr}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: JSONExtractOp, Right: yyDollar[3].expr}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: JSONUnquoteExtractOp, Right: yyDollar[3].expr}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 74:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr, Escape: yyDollar[5].expr}
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if value, ok := yyDollar[2].expr.(*Value); ok && value.Type == IntValue {
				yyVAL.expr = &Value{Type: IntValue, Value: append([]byte("-"), value.Value...)}
			} else {
				yyVAL.expr = &UnaryExpr{Operator: UMinusStr, Expr: yyDollar[2].expr}
			}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &UnaryExpr{Operator: UPlusStr, Expr: yyDollar[2].expr}
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &UnaryExpr{Operator: TildaStr, Expr: yyDollar[2].expr}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &AndExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &OrExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &IsExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &IsExpr{Left: yyDollar[1].expr, Right: &NotExpr{Expr: yyDollar[4].expr}}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &IsNullExpr{Expr: yyDollar[1].expr}
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &NotNullExpr{Expr: yyDollar[1].expr}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &NotNullExpr{Expr: yyDollar[1].expr}
		}
	case 85:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &BetweenExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, From: yyDollar[3].expr, To: yyDollar[5].expr}
		}
	case 86:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &CaseExpr{Expr: yyDollar[2].expr, Whens: yyDollar[3].whens, Else: yyDollar[4].expr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CollateExpr{Expr: yyDollar[1].expr, CollationName: string(yyDollar[3].bytes)}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].exprs
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: InStr, Right: yyDollar[3].colTuple}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: NotInStr, Right: yyDollar[4].colTuple}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].subquery
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 93:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &ConvertExpr{Expr: yyDollar[3].expr, Type: yyDollar[5].convertType}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &Value{Type: StrValue, Value: yyDollar[1].bytes[1 : len(yyDollar[1].bytes)-1]}
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &Value{Type: IntValue, Value: yyDollar[1].bytes}
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &Value{Type: FloatValue, Value: yyDollar[1].bytes}
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &Value{Type: BlobValue, Value: yyDollar[1].bytes}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &Value{Type: HexNumValue, Value: yyDollar[1].bytes}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = BoolValue(true)
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = BoolValue(false)
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &NullValue{}
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if len(yyDollar[1].bytes) > MaxColumnNameLength {
				yylex.Error(__yyfmt__.Sprintf("column length greater than %d", MaxColumnNameLength))
				return 1
			}
			yyVAL.column = &Column{Name: string(yyDollar[1].bytes)}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnList = ColumnList{yyDollar[1].column}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnList = append(yyDollar[1].columnList, yyDollar[3].column)
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = EqualStr
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = NotEqualStr
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = RegexpStr
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotRegexpStr
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GlobStr
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotGlobStr
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = MatchStr
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotMatchStr
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LessThanStr
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GreaterThanStr
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LessEqualStr
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GreaterEqualStr
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LikeStr
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotLikeStr
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = BetweenStr
		}
	case 122:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotBetweenStr
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = NoneStr
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = TextStr
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = RealStr
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = IntegerStr
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = NumericStr
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colTuple = Exprs{}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colTuple = yyDollar[1].subquery
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.colTuple = yyDollar[2].exprs
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.subquery = &Subquery{Select: yyDollar[2].selectStmt}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &ExistsExpr{Subquery: yyDollar[2].subquery}
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &NotExpr{Expr: &ExistsExpr{Subquery: yyDollar[3].subquery}}
		}
	case 134:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: &Column{Name: "glob"}, Args: Exprs{yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 135:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: &Column{Name: "like"}, Args: Exprs{yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 136:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: &Column{Name: "like"}, Args: Exprs{yyDollar[3].expr, yyDollar[5].expr, yyDollar[7].expr}}
		}
	case 137:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			if _, ok := AllowedFunctions[string(yyDollar[1].bytes)]; !ok {
				yylex.Error(__yyfmt__.Sprintf("function '%s' does not exist,", string(yyDollar[1].bytes)))
				return 1
			}
			yyVAL.expr = &FuncExpr{Name: &Column{Name: string(yyDollar[1].bytes)}, Distinct: yyDollar[3].bool, Args: yyDollar[4].exprs, Filter: yyDollar[6].where}
		}
	case 138:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			if _, ok := AllowedFunctions[string(yyDollar[1].bytes)]; !ok {
				yylex.Error(__yyfmt__.Sprintf("function '%s' does not exist", string(yyDollar[1].bytes)))
				return 1
			}
			yyVAL.expr = &FuncExpr{Name: &Column{Name: string(yyDollar[1].bytes)}, Distinct: false, Args: nil, Filter: yyDollar[5].where}
		}
	case 139:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = true
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.exprs = Exprs{yyDollar[1].expr}
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 143:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.exprs = nil
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 145:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 146:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.where = &Where{Type: WhereStr, Expr: yyDollar[4].expr}
		}
	case 147:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.expr = nil
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 149:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.when = &When{Condition: yyDollar[2].expr, Value: yyDollar[4].expr}
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.whens = []*When{yyDollar[1].when}
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = append(yyDollar[1].whens, yyDollar[2].when)
		}
	case 152:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.expr = nil
		}
	case 153:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	}
	goto yystack /* stack new state and value */
}
