// Code generated by goyacc -l -o yy_parser.go grammar.y. DO NOT EDIT.
package sqlparser

import __yyfmt__ "fmt"

import (
	"bytes"
	"strings"
)

var keywordsNotAllowed = map[string]struct{}{
	// We don't allow non-deterministic keywords as identifiers.
	"CURRENT_TIME":      {},
	"CURRENT_DATE":      {},
	"CURRENT_TIMESTAMP": {},

	// SQLite reserved keywords that are not part of Tableland spec.
	// We can't allow them as identifiers because it will throw an error in SQLite.
	//
	// SQLite has more reserved keywords (eg. CREATE, INSERT, ...). But those are part of the Tableland grammar,
	// that means that the parser already checks from them.
	//
	// These were identified by running the `TestReservedKeywords` test.
	"REFERENCES":    {},
	"ADD":           {},
	"ALTER":         {},
	"AUTOINCREMENT": {},
	"COMMIT":        {},
	"DEFERRABLE":    {},
	"DROP":          {},
	"FOREIGN":       {},
	"INDEX":         {},
	"RETURNING":     {},
	"TRANSACTION":   {},
}

func isRowID(column Identifier) bool {
	if strings.EqualFold(string(column), "rowid") || strings.EqualFold(string(column), "_rowid_") || strings.EqualFold(string(column), "oid") {
		return true
	}

	return false
}

type yySymType struct {
	yys                  int
	bool                 bool
	string               string
	bytes                []byte
	expr                 Expr
	exprs                Exprs
	column               *Column
	table                *Table
	convertType          ConvertType
	when                 *When
	whens                []*When
	selectColumn         SelectColumn
	selectColumnList     SelectColumnList
	readStmt             ReadStatement
	baseSelect           *Select
	where                *Where
	limit                *Limit
	orderBy              OrderBy
	orderingTerm         *OrderingTerm
	nulls                NullsType
	tableExpr            TableExpr
	joinTableExpr        *JoinTableExpr
	columnList           ColumnList
	indexedColumnList    IndexedColumnList
	indexedColumn        *IndexedColumn
	subquery             *Subquery
	colTuple             ColTuple
	statement            Statement
	identifier           Identifier
	createTableStmt      *CreateTable
	columnDefList        []*ColumnDef
	columnDef            *ColumnDef
	columnConstraint     ColumnConstraint
	columnConstraints    []ColumnConstraint
	value                *Value
	tableConstraint      TableConstraint
	tableConstraints     []TableConstraint
	insertStmt           *Insert
	insertRows           []Exprs
	deleteStmt           *Delete
	updateStmt           *Update
	updateExpression     *UpdateExpr
	updateList           []*UpdateExpr
	grant                *Grant
	revoke               *Revoke
	strings              []string
	privileges           Privileges
	stmts                []Statement
	upsertClause         Upsert
	onConflictClauseList []*OnConflictClause
	onConflictClause     *OnConflictClause
	onConflictTarget     *OnConflictTarget
	collateOpt           Identifier
	joinOperator         *JoinOperator
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGRAL = 57348
const HEXNUM = 57349
const FLOAT = 57350
const BLOBVAL = 57351
const ERROR = 57352
const TRUE = 57353
const FALSE = 57354
const NULL = 57355
const AND = 57356
const NONE = 57357
const INTEGER = 57358
const TEXT = 57359
const CAST = 57360
const AS = 57361
const CASE = 57362
const WHEN = 57363
const THEN = 57364
const ELSE = 57365
const END = 57366
const SELECT = 57367
const FROM = 57368
const WHERE = 57369
const GROUP = 57370
const BY = 57371
const HAVING = 57372
const LIMIT = 57373
const OFFSET = 57374
const ORDER = 57375
const ASC = 57376
const DESC = 57377
const NULLS = 57378
const FIRST = 57379
const LAST = 57380
const DISTINCT = 57381
const ALL = 57382
const EXISTS = 57383
const FILTER = 57384
const UNION = 57385
const EXCEPT = 57386
const INTERSECT = 57387
const CREATE = 57388
const TABLE = 57389
const INT = 57390
const BLOB = 57391
const ANY = 57392
const PRIMARY = 57393
const KEY = 57394
const UNIQUE = 57395
const CHECK = 57396
const DEFAULT = 57397
const GENERATED = 57398
const ALWAYS = 57399
const STORED = 57400
const VIRTUAL = 57401
const CONSTRAINT = 57402
const INSERT = 57403
const INTO = 57404
const VALUES = 57405
const DELETE = 57406
const UPDATE = 57407
const SET = 57408
const CONFLICT = 57409
const DO = 57410
const NOTHING = 57411
const GRANT = 57412
const TO = 57413
const REVOKE = 57414
const RIGHT = 57415
const FULL = 57416
const INNER = 57417
const LEFT = 57418
const NATURAL = 57419
const OUTER = 57420
const CROSS = 57421
const JOIN = 57422
const ON = 57423
const USING = 57424
const OR = 57425
const ANDOP = 57426
const NOT = 57427
const IS = 57428
const ISNOT = 57429
const MATCH = 57430
const GLOB = 57431
const REGEXP = 57432
const LIKE = 57433
const BETWEEN = 57434
const IN = 57435
const ISNULL = 57436
const NOTNULL = 57437
const NE = 57438
const LE = 57439
const GE = 57440
const INEQUALITY = 57441
const ESCAPE = 57442
const LSHIFT = 57443
const RSHIFT = 57444
const CONCAT = 57445
const JSON_EXTRACT_OP = 57446
const JSON_UNQUOTE_EXTRACT_OP = 57447
const COLLATE = 57448
const UNARY = 57449

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGRAL",
	"HEXNUM",
	"FLOAT",
	"BLOBVAL",
	"ERROR",
	"TRUE",
	"FALSE",
	"NULL",
	"AND",
	"'('",
	"','",
	"')'",
	"'.'",
	"';'",
	"NONE",
	"INTEGER",
	"TEXT",
	"CAST",
	"AS",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP",
	"BY",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"ORDER",
	"ASC",
	"DESC",
	"NULLS",
	"FIRST",
	"LAST",
	"DISTINCT",
	"ALL",
	"EXISTS",
	"FILTER",
	"UNION",
	"EXCEPT",
	"INTERSECT",
	"CREATE",
	"TABLE",
	"INT",
	"BLOB",
	"ANY",
	"PRIMARY",
	"KEY",
	"UNIQUE",
	"CHECK",
	"DEFAULT",
	"GENERATED",
	"ALWAYS",
	"STORED",
	"VIRTUAL",
	"CONSTRAINT",
	"INSERT",
	"INTO",
	"VALUES",
	"DELETE",
	"UPDATE",
	"SET",
	"CONFLICT",
	"DO",
	"NOTHING",
	"GRANT",
	"TO",
	"REVOKE",
	"RIGHT",
	"FULL",
	"INNER",
	"LEFT",
	"NATURAL",
	"OUTER",
	"CROSS",
	"JOIN",
	"ON",
	"USING",
	"OR",
	"ANDOP",
	"NOT",
	"IS",
	"ISNOT",
	"MATCH",
	"GLOB",
	"REGEXP",
	"LIKE",
	"BETWEEN",
	"IN",
	"ISNULL",
	"NOTNULL",
	"NE",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"INEQUALITY",
	"ESCAPE",
	"'&'",
	"'|'",
	"LSHIFT",
	"RSHIFT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"CONCAT",
	"JSON_EXTRACT_OP",
	"JSON_UNQUOTE_EXTRACT_OP",
	"COLLATE",
	"'~'",
	"UNARY",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 70,
	18, 83,
	-2, 130,
	-1, 183,
	78, 55,
	79, 55,
	80, 55,
	81, 55,
	-2, 35,
	-1, 184,
	78, 55,
	79, 55,
	80, 55,
	81, 55,
	-2, 36,
	-1, 252,
	16, 187,
	17, 187,
	-2, 200,
	-1, 311,
	16, 188,
	17, 188,
	-2, 200,
}

const yyPrivate = 57344

const yyLast = 1632

var yyAct = [...]int16{
	281, 454, 160, 436, 419, 58, 347, 71, 235, 280,
	340, 267, 368, 307, 306, 312, 268, 371, 179, 260,
	299, 183, 158, 163, 222, 215, 147, 5, 184, 125,
	452, 123, 94, 56, 91, 351, 241, 41, 59, 101,
	102, 103, 104, 105, 110, 111, 112, 123, 39, 90,
	229, 95, 65, 37, 103, 104, 105, 110, 111, 112,
	123, 141, 142, 143, 145, 146, 52, 57, 54, 47,
	84, 85, 132, 133, 134, 135, 348, 275, 106, 107,
	108, 109, 101, 102, 103, 104, 105, 110, 111, 112,
	123, 110, 111, 112, 123, 369, 370, 409, 408, 56,
	407, 375, 187, 188, 189, 190, 191, 192, 193, 194,
	195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
	181, 228, 167, 213, 169, 165, 168, 318, 345, 365,
	150, 262, 327, 57, 185, 180, 106, 107, 108, 109,
	101, 102, 103, 104, 105, 110, 111, 112, 123, 226,
	262, 326, 88, 88, 231, 232, 218, 70, 372, 219,
	237, 359, 173, 361, 362, 363, 364, 182, 206, 242,
	262, 244, 245, 240, 447, 95, 38, 217, 446, 220,
	432, 388, 457, 238, 320, 321, 322, 319, 42, 38,
	86, 44, 43, 38, 38, 360, 236, 265, 348, 263,
	261, 234, 35, 236, 266, 230, 276, 246, 273, 233,
	39, 220, 308, 272, 138, 274, 265, 157, 263, 261,
	403, 185, 89, 87, 285, 455, 456, 353, 31, 354,
	355, 395, 392, 277, 341, 152, 265, 288, 263, 261,
	25, 51, 298, 27, 166, 38, 283, 38, 210, 209,
	208, 211, 212, 207, 166, 33, 34, 38, 302, 303,
	217, 248, 156, 296, 301, 48, 313, 420, 421, 305,
	315, 308, 15, 316, 50, 159, 328, 259, 165, 329,
	410, 214, 317, 243, 138, 333, 324, 98, 323, 180,
	92, 342, 343, 9, 266, 185, 16, 36, 166, 17,
	18, 185, 99, 349, 15, 19, 332, 20, 16, 223,
	426, 17, 18, 254, 255, 166, 366, 19, 24, 20,
	22, 8, 166, 39, 357, 313, 367, 358, 172, 223,
	166, 284, 378, 350, 186, 379, 376, 377, 373, 374,
	336, 338, 337, 270, 38, 253, 256, 257, 49, 15,
	381, 450, 449, 387, 72, 81, 83, 82, 73, 140,
	74, 75, 76, 7, 398, 132, 133, 134, 135, 399,
	405, 106, 107, 108, 109, 101, 102, 103, 104, 105,
	110, 111, 112, 123, 39, 271, 411, 380, 46, 294,
	448, 40, 294, 444, 339, 418, 412, 166, 422, 423,
	415, 325, 417, 304, 269, 427, 294, 438, 166, 424,
	425, 429, 45, 39, 139, 428, 331, 434, 38, 27,
	331, 431, 289, 433, 38, 225, 331, 270, 352, 28,
	29, 30, 236, 126, 331, 389, 331, 330, 294, 297,
	294, 295, 309, 453, 250, 236, 39, 39, 239, 174,
	442, 416, 166, 236, 459, 437, 460, 164, 186, 414,
	463, 406, 401, 402, 464, 404, 356, 397, 394, 393,
	390, 458, 386, 382, 293, 216, 151, 154, 153, 149,
	148, 96, 396, 270, 39, 271, 465, 39, 139, 437,
	81, 83, 82, 391, 300, 39, 165, 117, 116, 121,
	118, 1, 131, 130, 129, 136, 137, 124, 119, 120,
	128, 127, 132, 133, 134, 135, 413, 346, 106, 107,
	108, 109, 101, 102, 103, 104, 105, 110, 111, 112,
	123, 21, 344, 4, 2, 14, 23, 13, 162, 385,
	384, 161, 12, 11, 292, 10, 249, 251, 310, 311,
	178, 166, 264, 227, 435, 155, 97, 247, 93, 221,
	335, 314, 53, 451, 166, 100, 26, 252, 32, 175,
	122, 115, 166, 114, 166, 113, 258, 287, 400, 66,
	282, 144, 69, 68, 6, 3, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 176, 177, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 166, 170,
	461, 117, 116, 121, 118, 166, 131, 130, 129, 136,
	137, 124, 119, 120, 128, 127, 132, 133, 134, 135,
	171, 0, 106, 107, 108, 109, 101, 102, 103, 104,
	105, 110, 111, 112, 123, 117, 116, 121, 118, 462,
	131, 130, 129, 136, 137, 124, 119, 120, 128, 127,
	132, 133, 134, 135, 0, 0, 106, 107, 108, 109,
	101, 102, 103, 104, 105, 110, 111, 112, 123, 0,
	0, 117, 116, 121, 118, 445, 131, 130, 129, 136,
	137, 124, 119, 120, 128, 127, 132, 133, 134, 135,
	0, 0, 106, 107, 108, 109, 101, 102, 103, 104,
	105, 110, 111, 112, 123, 0, 0, 0, 0, 443,
	117, 116, 121, 118, 0, 131, 130, 129, 136, 137,
	124, 119, 120, 128, 127, 132, 133, 134, 135, 0,
	0, 106, 107, 108, 109, 101, 102, 103, 104, 105,
	110, 111, 112, 123, 441, 0, 117, 116, 121, 118,
	0, 131, 130, 129, 136, 137, 124, 119, 120, 128,
	127, 132, 133, 134, 135, 0, 0, 106, 107, 108,
	109, 101, 102, 103, 104, 105, 110, 111, 112, 123,
	117, 116, 121, 118, 440, 131, 130, 129, 136, 137,
	124, 119, 120, 128, 127, 132, 133, 134, 135, 0,
	0, 106, 107, 108, 109, 101, 102, 103, 104, 105,
	110, 111, 112, 123, 0, 117, 116, 121, 118, 439,
	131, 130, 129, 136, 137, 124, 119, 120, 128, 127,
	132, 133, 134, 135, 0, 0, 106, 107, 108, 109,
	101, 102, 103, 104, 105, 110, 111, 112, 123, 0,
	0, 0, 0, 430, 0, 117, 116, 121, 118, 0,
	131, 130, 129, 136, 137, 124, 119, 120, 128, 127,
	132, 133, 134, 135, 0, 0, 106, 107, 108, 109,
	101, 102, 103, 104, 105, 110, 111, 112, 123, 383,
	117, 116, 121, 118, 0, 131, 130, 129, 136, 137,
	124, 119, 120, 128, 127, 132, 133, 134, 135, 0,
	0, 106, 107, 108, 109, 101, 102, 103, 104, 105,
	110, 111, 112, 123, 117, 116, 121, 118, 0, 131,
	130, 129, 136, 137, 124, 119, 120, 128, 127, 132,
	133, 134, 135, 334, 0, 106, 107, 108, 109, 101,
	102, 103, 104, 105, 110, 111, 112, 123, 0, 0,
	117, 116, 121, 118, 0, 131, 130, 129, 136, 137,
	124, 119, 120, 128, 127, 132, 133, 134, 135, 291,
	0, 106, 107, 108, 109, 101, 102, 103, 104, 105,
	110, 111, 112, 123, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 117, 116, 121, 118, 0, 131,
	130, 129, 136, 137, 124, 119, 120, 128, 127, 132,
	133, 134, 135, 290, 0, 106, 107, 108, 109, 101,
	102, 103, 104, 105, 110, 111, 112, 123, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 117, 116, 121, 118, 0, 131, 130, 129, 136,
	137, 124, 119, 120, 128, 127, 132, 133, 134, 135,
	286, 0, 106, 107, 108, 109, 101, 102, 103, 104,
	105, 110, 111, 112, 123, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 278, 117, 116, 121, 118, 0,
	131, 130, 129, 136, 137, 124, 119, 120, 128, 127,
	132, 133, 134, 135, 0, 0, 106, 107, 108, 109,
	101, 102, 103, 104, 105, 110, 111, 112, 123, 0,
	0, 224, 0, 0, 117, 116, 121, 118, 0, 131,
	130, 129, 136, 137, 124, 119, 120, 128, 127, 132,
	133, 134, 135, 0, 0, 106, 107, 108, 109, 101,
	102, 103, 104, 105, 110, 111, 112, 123, 117, 116,
	121, 118, 0, 131, 130, 129, 136, 137, 124, 119,
	120, 128, 127, 132, 133, 134, 135, 0, 0, 106,
	107, 108, 109, 101, 102, 103, 104, 105, 110, 111,
	112, 123, 117, 116, 121, 118, 0, 131, 130, 129,
	136, 137, 124, 119, 120, 128, 127, 132, 133, 134,
	135, 0, 0, 106, 107, 108, 109, 101, 102, 103,
	104, 105, 110, 111, 112, 123, 117, 116, 121, 118,
	0, 131, 130, 129, 136, 137, 124, 119, 120, 128,
	127, 132, 133, 134, 135, 0, 0, 106, 107, 108,
	109, 101, 102, 103, 104, 105, 110, 111, 112, 123,
	116, 121, 118, 0, 131, 130, 129, 136, 137, 124,
	119, 120, 128, 127, 132, 133, 134, 135, 0, 0,
	106, 107, 108, 109, 101, 102, 103, 104, 105, 110,
	111, 112, 123, 121, 118, 0, 131, 130, 129, 136,
	137, 124, 119, 120, 128, 127, 132, 133, 134, 135,
	0, 0, 106, 107, 108, 109, 101, 102, 103, 104,
	105, 110, 111, 112, 123, 39, 72, 81, 83, 82,
	73, 0, 74, 75, 76, 0, 64, 0, 279, 0,
	0, 0, 0, 0, 67, 0, 63, 0, 0, 0,
	0, 15, 39, 72, 81, 83, 82, 73, 0, 74,
	75, 76, 0, 64, 0, 0, 0, 77, 0, 0,
	0, 67, 0, 63, 39, 72, 81, 83, 82, 73,
	0, 74, 75, 76, 0, 64, 0, 0, 0, 0,
	0, 0, 0, 67, 77, 63, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 78, 0, 0, 0, 79, 77, 80, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 61, 60, 0, 0, 78, 0,
	205, 0, 79, 62, 80, 0, 39, 72, 81, 83,
	82, 73, 0, 74, 75, 76, 0, 64, 0, 0,
	78, 61, 60, 0, 79, 67, 80, 63, 0, 0,
	62, 0, 15, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 61, 60, 55, 0, 0, 77, 0,
	0, 0, 62, 39, 72, 81, 83, 82, 73, 0,
	74, 75, 76, 0, 64, 0, 0, 0, 0, 0,
	0, 0, 67, 0, 63, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 78, 0, 0, 77, 79, 0, 80, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 61, 60, 0, 0, 0,
	0, 0, 0, 0, 62, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 78,
	0, 0, 0, 79, 0, 80, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 61, 60, 0, 0, 0, 0, 0, 0,
	0, 62,
}

var yyPact = [...]int16{
	242, -1000, -1000, 301, 299, -1000, -1000, -1000, 381, 176,
	-1000, -1000, -1000, -1000, -1000, 211, 135, 266, 491, 122,
	122, -1000, -1000, -1000, 230, 229, 274, 240, 196, -1000,
	-1000, 491, 1390, -1000, -1000, 491, 491, 119, -1000, -1000,
	137, -1000, -1000, -1000, -1000, 136, -1000, -1000, 1509, 205,
	1509, -1000, 466, 271, -1000, -1000, 409, 341, -1000, -1000,
	1509, 1509, 1509, 1509, 1462, -1000, -1000, 465, -1000, -1000,
	464, -1000, -1000, -1000, -1000, -1000, -1000, 461, 189, 463,
	462, -1000, -1000, -1000, 202, 243, 442, 491, 122, 491,
	593, 310, 229, 433, -1000, 557, 491, 243, 1390, 443,
	-1000, 1509, 1509, 1509, 1509, 1509, 1509, 1509, 1509, 1509,
	1509, 1509, 1509, 1509, 1509, 1509, 1509, 1509, 1368, -1000,
	-1000, 155, 1509, 491, 460, -1000, 483, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	44, -1000, -1000, -1000, 283, 1158, 1124, 408, 1509, 6,
	-1000, 274, 461, 1509, 1509, 141, 133, 491, -1000, 1509,
	243, 432, -1000, -1000, 491, -66, -1000, 93, -1000, 252,
	1509, 1509, 491, -1000, 1509, 220, -1000, -1000, 428, -1000,
	292, 244, -1000, 154, 154, 380, 319, -61, -61, -27,
	-27, -27, -74, -74, -74, -74, -90, -90, -90, 262,
	27, -31, 1223, 1191, 262, 1509, -1000, 460, -1000, -1000,
	-1000, -1000, -1000, 1090, -1000, -1000, 1341, -1000, -1000, -1000,
	-1000, 303, -1000, 1509, -1000, -1000, 1056, 1509, 405, -1000,
	-1000, 1017, 973, 459, -1000, 424, -1000, 1158, -1000, 491,
	422, 1509, 489, 489, 1158, 1158, -1000, -1000, 216, 386,
	206, 426, 147, -1000, -1000, -1000, -1000, -1000, 235, 239,
	443, -1000, -1000, 42, 106, -1000, 443, -1000, -1000, 480,
	-1000, -1000, 384, 134, 115, 1509, 262, -1000, 1509, -1000,
	420, 1158, 277, -1000, 1509, 926, 320, 377, 410, 187,
	1509, 1509, 112, 1509, 491, -1000, -1000, -67, 1158, 412,
	-1000, 412, -1000, -1000, -1000, -1000, -1000, 171, 491, 147,
	-1000, 147, -1000, 105, -1000, 1509, 1509, 9, -1000, 75,
	75, 75, 16, 9, -1000, 380, -1000, -1000, 262, 262,
	-1000, 1509, -1000, 1158, 1509, 370, -1000, -1000, -1000, 187,
	-1000, 458, 882, 523, -1000, 457, -10, -1000, 109, 418,
	-1000, 455, 488, 175, 454, 453, -1000, -1000, -1000, 174,
	469, -1000, 452, 349, 158, 450, 1158, 410, -1000, 1509,
	446, 15, -1000, 13, 12, -1000, -1000, -1000, 1158, 1158,
	-1000, -1000, 248, -1000, -1000, 1509, 1509, -1000, 444, -1000,
	1509, -1000, 436, 491, 1509, 228, -1000, 1509, 1509, -1000,
	-1000, 484, 484, 286, 1509, 1158, 491, -1000, -1000, -1000,
	1509, 846, 404, 107, 491, 400, 491, 390, 812, -1000,
	-1000, -1000, 777, 737, -1000, -1000, 435, 702, 376, 668,
	-1000, -1000, 104, 373, -1000, 335, -1000, -91, -1000, -1000,
	-1000, -1000, 1509, 162, -1000, -1000, -1000, 111, 243, -1000,
	491, 228, 491, 632, -1000, -1000, -1000, 442, -1000, -1000,
	-1000, -1000, 162, 243, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 363, 585, 26, 321, 584, 0, 5, 583, 582,
	581, 580, 579, 578, 9, 577, 576, 575, 573, 571,
	570, 569, 568, 567, 4, 37, 566, 38, 565, 29,
	11, 16, 13, 157, 563, 68, 562, 34, 22, 561,
	10, 560, 24, 559, 69, 240, 558, 32, 557, 21,
	556, 28, 12, 8, 555, 554, 3, 52, 25, 553,
	1, 552, 17, 550, 18, 15, 549, 548, 7, 14,
	547, 546, 545, 544, 543, 542, 23, 2, 541, 538,
	537, 535, 20, 391, 534, 533, 532, 517, 6, 516,
	19, 501, 531,
}

var yyR1 = [...]int8{
	0, 91, 84, 84, 2, 2, 85, 85, 1, 1,
	1, 1, 1, 92, 92, 3, 3, 26, 26, 26,
	26, 4, 22, 22, 22, 36, 36, 35, 35, 35,
	28, 28, 28, 29, 29, 50, 50, 49, 49, 49,
	49, 30, 30, 30, 31, 31, 51, 51, 90, 90,
	90, 90, 90, 90, 90, 61, 61, 62, 62, 52,
	52, 52, 38, 38, 16, 16, 39, 39, 45, 45,
	46, 46, 47, 21, 21, 21, 48, 48, 48, 44,
	44, 44, 44, 37, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
	27, 53, 53, 17, 17, 17, 17, 17, 17, 17,
	17, 18, 18, 18, 18, 19, 19, 20, 20, 41,
	41, 41, 58, 58, 58, 57, 12, 12, 8, 8,
	8, 9, 9, 59, 59, 14, 14, 15, 15, 40,
	40, 10, 10, 42, 43, 43, 11, 11, 5, 63,
	63, 64, 23, 23, 23, 23, 23, 67, 67, 66,
	66, 65, 65, 65, 65, 65, 65, 65, 65, 65,
	32, 32, 24, 24, 24, 13, 13, 68, 68, 68,
	60, 60, 60, 71, 71, 70, 70, 69, 69, 69,
	55, 55, 56, 34, 34, 72, 72, 54, 54, 73,
	73, 86, 86, 87, 87, 88, 88, 89, 89, 74,
	75, 77, 77, 78, 78, 79, 76, 80, 81, 82,
	82, 83, 83, 25, 25, 25, 33,
}

var yyR2 = [...]int8{
	0, 1, 2, 2, 1, 1, 1, 3, 1, 1,
	1, 1, 1, 0, 1, 3, 5, 1, 2, 1,
	1, 7, 0, 1, 1, 1, 3, 1, 2, 3,
	0, 1, 2, 1, 1, 2, 2, 2, 4, 3,
	3, 0, 1, 2, 1, 1, 4, 4, 1, 1,
	2, 4, 4, 4, 3, 0, 1, 0, 1, 0,
	2, 4, 0, 2, 0, 3, 0, 2, 0, 3,
	1, 3, 3, 0, 1, 1, 0, 2, 2, 0,
	2, 4, 4, 1, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 5, 2, 2, 2, 3, 3, 3, 4,
	2, 2, 3, 5, 5, 3, 3, 3, 4, 1,
	1, 6, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 1, 1, 1, 2, 1, 2, 1,
	2, 1, 1, 1, 1, 1, 2, 1, 2, 1,
	1, 1, 2, 1, 3, 3, 2, 3, 6, 6,
	8, 6, 5, 0, 1, 1, 3, 0, 1, 0,
	5, 0, 1, 4, 1, 2, 0, 2, 7, 1,
	3, 3, 1, 1, 1, 1, 1, 0, 1, 1,
	2, 4, 3, 2, 5, 5, 3, 3, 8, 6,
	0, 2, 0, 1, 1, 2, 2, 1, 1, 1,
	0, 1, 1, 0, 1, 2, 3, 6, 5, 5,
	1, 3, 3, 0, 2, 7, 5, 0, 3, 3,
	5, 0, 1, 1, 2, 5, 8, 0, 4, 4,
	5, 1, 1, 1, 3, 7, 3, 6, 6, 1,
	3, 1, 3, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -91, -84, -2, -85, -3, -5, -1, -4, 51,
	-72, -74, -75, -80, -81, 30, 66, 69, 70, 75,
	77, -92, 19, -92, 19, -45, -26, 38, 48, 49,
	50, 52, -22, 44, 45, 67, 31, -37, -33, 4,
	-83, -25, 66, 70, 69, -83, -1, -44, 36, -4,
	34, 45, -37, -36, -35, 115, -6, -37, -7, -27,
	114, 113, 122, 25, 15, -57, -12, 23, -8, -9,
	-33, -68, 5, 9, 11, 12, 13, 46, 90, 94,
	96, 6, 8, 7, -37, -37, 71, 86, 16, 86,
	-6, -37, -45, -46, -47, -6, 15, -50, 16, 31,
	-28, 113, 114, 115, 116, 117, 109, 110, 111, 112,
	118, 119, 120, -17, -18, -19, 89, 88, 91, 99,
	100, 90, -20, 121, 98, -29, 24, 102, 101, 95,
	94, 93, 103, 104, 105, 106, 96, 97, -33, 5,
	18, -6, -6, -6, -10, -6, -6, -3, 15, 15,
	-57, 15, 46, 15, 15, -54, 60, 15, -38, 32,
	-77, -78, -79, -76, 15, -27, -33, -37, -25, -37,
	16, 37, 18, -44, 16, -21, 39, 40, -63, -64,
	-27, -38, -35, -49, -51, -37, 15, -6, -6, -6,
	-6, -6, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, -6, -6, -6, -6, 92, 13, 98, 95, 94,
	93, 96, 97, -6, -33, -58, 15, -57, -29, 115,
	-27, -43, -42, 26, 17, 17, -6, -59, 115, 44,
	-57, -6, -6, 68, 68, -53, -27, -6, -38, 16,
	-53, 102, 76, 31, -6, -6, -47, -48, 41, -71,
	16, -70, -23, 53, 21, 22, 54, 55, -16, 33,
	-90, 85, 16, 84, -61, 82, -90, -30, -31, 24,
	-33, 5, -3, -49, -51, 108, -6, -58, 14, 17,
	-14, -6, -11, -42, 28, -6, 24, -15, -14, 17,
	16, 16, -73, 15, 16, 17, -76, 17, -6, -82,
	5, -82, 42, 43, 17, -64, -69, -32, 65, 16,
	-67, -66, -65, -32, -39, 35, 34, -49, 85, 81,
	78, 79, 80, -49, -31, 17, 17, 17, -6, -6,
	17, 16, 29, -6, 27, -41, 20, 22, 21, 17,
	-40, 47, -6, -6, -86, 16, -87, -88, 86, -14,
	-27, 102, 16, 56, 58, 59, -33, -69, -65, 56,
	90, 58, 59, 60, 61, 24, -6, -14, -52, 86,
	87, -62, 83, -62, -62, 85, -52, -30, -6, -6,
	17, -40, 15, 17, 17, 16, 15, -88, 72, 17,
	15, 5, 57, 15, 15, 57, 13, 15, 15, -7,
	-13, 113, 114, 62, 15, -6, 15, 85, 85, 85,
	32, -6, -14, -89, 15, -14, 15, -53, -6, -24,
	39, 40, -6, -6, -68, -68, 24, -6, -53, -6,
	17, 17, 73, -53, 17, -55, -56, -27, 17, 17,
	17, 17, 15, 17, 17, 17, 74, 70, 17, 17,
	16, -34, 121, -6, -60, 63, 64, 71, -38, -56,
	-24, -33, 17, -77, -60, -38,
}

var yyDef = [...]int16{
	0, -2, 1, 13, 13, 4, 5, 6, 68, 0,
	8, 9, 10, 11, 12, 22, 0, 0, 0, 0,
	0, 2, 14, 3, 14, 79, 0, 0, 17, 19,
	20, 0, 0, 23, 24, 0, 0, 0, 83, 256,
	0, 251, 253, 254, 255, 0, 7, 15, 0, 68,
	0, 18, 0, 0, 25, 27, 30, 0, 84, 85,
	0, 0, 0, 171, 0, 119, 120, 0, 122, 123,
	-2, 124, 125, 126, 127, 128, 129, 0, 0, 0,
	0, 207, 208, 209, 227, 62, 0, 0, 0, 0,
	80, 0, 79, 69, 70, 73, 0, 62, 0, 0,
	28, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 110,
	111, 0, 0, 0, 0, 31, 0, 133, 134, 135,
	137, 139, 141, 142, 143, 144, 145, 147, 33, 34,
	0, 103, 104, 105, 0, 172, 0, 0, 0, 163,
	156, 0, 0, 0, 0, 0, 0, 0, 239, 0,
	62, 241, 242, 243, 0, 0, 130, 0, 252, 0,
	0, 0, 0, 16, 0, 76, 74, 75, 213, 179,
	0, 64, 26, -2, -2, 41, 0, 87, 88, 89,
	90, 91, 92, 93, 94, 95, 96, 97, 98, 99,
	100, 101, 106, 107, 108, 0, 112, 0, 136, 138,
	140, 146, 148, 0, 115, 117, 0, 153, 32, 29,
	86, 176, 174, 0, 116, 155, 0, 167, 0, 164,
	157, 0, 0, 0, 226, 0, 131, 63, 240, 0,
	0, 0, 0, 0, 81, 82, 71, 72, 0, 0,
	200, 214, -2, 182, 183, 184, 185, 186, 66, 0,
	0, 48, 49, 0, 0, 56, 0, 37, 42, 0,
	44, 45, 0, 55, 55, 0, 109, 118, 0, 152,
	0, 165, 0, 175, 0, 0, 0, 0, 168, 169,
	0, 0, 231, 0, 0, 228, 244, 0, 246, 247,
	249, 248, 77, 78, 178, 180, 215, 0, 0, 200,
	181, -2, 189, 0, 21, 0, 0, 59, 50, 57,
	57, 57, 0, 59, 43, 41, 39, 40, 102, 113,
	154, 0, 114, 177, 0, 0, 149, 150, 151, 169,
	162, 0, 0, 0, 225, 0, 232, 233, 0, 0,
	132, 0, 0, 0, 0, 0, 201, 216, 190, 0,
	0, 193, 0, 0, 0, 0, 67, 65, 46, 0,
	0, 0, 58, 0, 0, 54, 47, 38, 166, 173,
	121, 161, 0, 158, 159, 0, 0, 234, 237, 229,
	0, 250, 0, 0, 0, 202, 192, 0, 0, 196,
	197, 0, 0, 0, 0, 60, 0, 51, 52, 53,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 191,
	203, 204, 0, 0, 205, 206, 0, 0, 0, 0,
	160, 230, 0, 0, 245, 0, 220, 223, 218, 219,
	194, 195, 0, 210, 61, 170, 235, 0, 62, 217,
	0, 202, 0, 0, 199, 211, 212, 0, 238, 221,
	222, 224, 210, 62, 198, 236,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 117, 109, 3,
	15, 17, 115, 113, 16, 114, 18, 116, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 19,
	103, 102, 104, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 110, 3, 122,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 20, 21, 22, 23, 24, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
	47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
	57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
	67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
	77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 101, 105, 106, 107, 108, 111,
	112, 118, 119, 120, 121, 123,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).ast = &AST{Statements: yyDollar[1].stmts}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.stmts = []Statement{yyDollar[1].statement}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.statement = yyDollar[1].readStmt
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.statement = yyDollar[1].createTableStmt
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmts = []Statement{yyDollar[1].statement}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[3].statement)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).statementIdx++
			yyVAL.statement = yyDollar[1].insertStmt
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).statementIdx++
			yyVAL.statement = yyDollar[1].deleteStmt
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).statementIdx++
			yyVAL.statement = yyDollar[1].updateStmt
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).statementIdx++
			yyVAL.statement = yyDollar[1].grant
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).statementIdx++
			yyVAL.statement = yyDollar[1].revoke
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].baseSelect.OrderBy = yyDollar[2].orderBy
			yyDollar[1].baseSelect.Limit = yyDollar[3].limit
			yyVAL.readStmt = yyDollar[1].baseSelect
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.readStmt = &CompoundSelect{Type: yyDollar[2].string, Left: yyDollar[1].baseSelect, Right: yyDollar[3].baseSelect, OrderBy: yyDollar[4].orderBy, Limit: yyDollar[5].limit}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = CompoundUnionStr
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = CompoundUnionAllStr
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = CompoundExceptStr
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = CompoundIntersectStr
		}
	case 21:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.baseSelect = &Select{
				Distinct:         yyDollar[2].string,
				SelectColumnList: yyDollar[3].selectColumnList,
				From:             yyDollar[4].tableExpr,
				Where:            yyDollar[5].where,
				GroupBy:          GroupBy(yyDollar[6].exprs),
				Having:           yyDollar[7].where,
			}
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = ""
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = DistinctStr
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = AllStr
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.selectColumnList = SelectColumnList{yyDollar[1].selectColumn}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.selectColumnList = append(yyDollar[1].selectColumnList, yyDollar[3].selectColumn)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.selectColumn = &StarSelectColumn{}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.selectColumn = &AliasedSelectColumn{Expr: yyDollar[1].expr, As: yyDollar[2].identifier}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.selectColumn = &StarSelectColumn{TableRef: yyDollar[1].table}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.identifier = Identifier("")
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.identifier = yyDollar[2].identifier
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = Identifier(string(yyDollar[1].bytes[1 : len(yyDollar[1].bytes)-1]))
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[2].tableExpr
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[2].joinTableExpr
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: yyDollar[1].table, As: yyDollar[2].identifier}
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: &Subquery{Select: yyDollar[2].readStmt}, As: yyDollar[4].identifier}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExpr = &ParenTableExpr{TableExpr: yyDollar[2].tableExpr}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[2].joinTableExpr
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.identifier = Identifier("")
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.identifier = yyDollar[2].identifier
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.identifier = Identifier(string(yyDollar[1].bytes[1 : len(yyDollar[1].bytes)-1]))
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].joinTableExpr == nil {
				yyVAL.joinTableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, JoinOperator: yyDollar[2].joinOperator, RightExpr: yyDollar[3].tableExpr}
			} else {
				yyDollar[4].joinTableExpr.LeftExpr = yyDollar[1].tableExpr
				yyDollar[4].joinTableExpr.JoinOperator = yyDollar[2].joinOperator
				yyDollar[4].joinTableExpr.RightExpr = yyDollar[3].tableExpr
				yyVAL.joinTableExpr = yyDollar[4].joinTableExpr
			}
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].joinTableExpr == nil {
				yyVAL.joinTableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].joinTableExpr, JoinOperator: yyDollar[2].joinOperator, RightExpr: yyDollar[3].tableExpr}
			} else {
				yyDollar[4].joinTableExpr.LeftExpr = yyDollar[1].joinTableExpr
				yyDollar[4].joinTableExpr.JoinOperator = yyDollar[2].joinOperator
				yyDollar[4].joinTableExpr.RightExpr = yyDollar[3].tableExpr
				yyVAL.joinTableExpr = yyDollar[4].joinTableExpr
			}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: JoinStr}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: JoinStr}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: JoinStr}
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: LeftJoinStr, Natural: yyDollar[1].bool, Outer: yyDollar[3].bool}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: RightJoinStr, Natural: yyDollar[1].bool, Outer: yyDollar[3].bool}
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: FullJoinStr, Natural: yyDollar[1].bool, Outer: yyDollar[3].bool}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.joinOperator = &JoinOperator{Op: InnerJoinStr, Natural: yyDollar[1].bool}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = true
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = true
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.joinTableExpr = nil
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.joinTableExpr = &JoinTableExpr{On: yyDollar[2].expr}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.joinTableExpr = &JoinTableExpr{Using: yyDollar[3].columnList}
		}
	case 62:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.where = NewWhere(WhereStr, yyDollar[2].expr)
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.exprs = nil
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.exprs = yyDollar[3].exprs
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.where = NewWhere(HavingStr, yyDollar[2].expr)
		}
	case 68:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.orderBy = nil
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderBy = yyDollar[3].orderBy
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.orderBy = OrderBy{yyDollar[1].orderingTerm}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderBy = append(yyDollar[1].orderBy, yyDollar[3].orderingTerm)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.orderingTerm = &OrderingTerm{Expr: yyDollar[1].expr, Direction: yyDollar[2].string, Nulls: yyDollar[3].nulls}
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = AscStr
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = AscStr
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = DescStr
		}
	case 76:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nulls = NullsNil
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nulls = NullsFirst
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nulls = NullsLast
		}
	case 79:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.limit = nil
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.limit = &Limit{Limit: yyDollar[2].expr}
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.limit = &Limit{Offset: yyDollar[2].expr, Limit: yyDollar[4].expr}
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.limit = &Limit{Offset: yyDollar[4].expr, Limit: yyDollar[2].expr}
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.table = &Table{Name: yyDollar[1].identifier}
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].column
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[3].column.TableRef = yyDollar[1].table
			yyVAL.expr = yyDollar[3].column
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: PlusStr, Right: yyDollar[3].expr}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: MinusStr, Right: yyDollar[3].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: MultStr, Right: yyDollar[3].expr}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: DivStr, Right: yyDollar[3].expr}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ModStr, Right: yyDollar[3].expr}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: BitAndStr, Right: yyDollar[3].expr}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: BitOrStr, Right: yyDollar[3].expr}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ShiftLeftStr, Right: yyDollar[3].expr}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ShiftRightStr, Right: yyDollar[3].expr}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: ConcatStr, Right: yyDollar[3].expr}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: JSONExtractOp, Right: yyDollar[3].expr}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &BinaryExpr{Left: yyDollar[1].expr, Operator: JSONUnquoteExtractOp, Right: yyDollar[3].expr}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr}
		}
	case 102:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, Right: yyDollar[3].expr, Escape: yyDollar[5].expr}
		}
	case 103:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if value, ok := yyDollar[2].expr.(*Value); ok && value.Type == IntValue {
				yyVAL.expr = &Value{Type: IntValue, Value: append([]byte("-"), value.Value...)}
			} else {
				yyVAL.expr = &UnaryExpr{Operator: UMinusStr, Expr: yyDollar[2].expr}
			}
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &UnaryExpr{Operator: UPlusStr, Expr: yyDollar[2].expr}
		}
	case 105:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &UnaryExpr{Operator: TildaStr, Expr: yyDollar[2].expr}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &AndExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &OrExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &IsExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 109:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &IsExpr{Left: yyDollar[1].expr, Right: &NotExpr{Expr: yyDollar[4].expr}}
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &IsNullExpr{Expr: yyDollar[1].expr}
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &NotNullExpr{Expr: yyDollar[1].expr}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &NotNullExpr{Expr: yyDollar[1].expr}
		}
	case 113:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &BetweenExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].string, From: yyDollar[3].expr, To: yyDollar[5].expr}
		}
	case 114:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &CaseExpr{Expr: yyDollar[2].expr, Whens: yyDollar[3].whens, Else: yyDollar[4].expr}
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CollateExpr{Expr: yyDollar[1].expr, CollationName: yyDollar[3].identifier}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &ParenExpr{Expr: yyDollar[2].expr}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: InStr, Right: yyDollar[3].colTuple}
		}
	case 118:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &CmpExpr{Left: yyDollar[1].expr, Operator: NotInStr, Right: yyDollar[4].colTuple}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].subquery
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 121:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &ConvertExpr{Expr: yyDollar[3].expr, Type: yyDollar[5].convertType}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].value
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			str := yyDollar[1].bytes[1 : len(yyDollar[1].bytes)-1]
			if len(str) > MaxTextLength {
				yylex.(*Lexer).AddError(&ErrTextTooLong{Length: len(str), MaxAllowed: MaxTextLength})
			}
			yyVAL.expr = &Value{Type: StrValue, Value: str}
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if len(yyDollar[1].bytes) > MaxBlobLength {
				yylex.(*Lexer).AddError(&ErrBlobTooBig{Length: len(yyDollar[1].bytes), MaxAllowed: MaxBlobLength})
			}
			yyVAL.expr = &Value{Type: BlobValue, Value: yyDollar[1].bytes}
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = BoolValue(true)
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = BoolValue(false)
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &NullValue{}
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.column = &Column{Name: Identifier(string(yyDollar[1].identifier))}
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnList = ColumnList{yyDollar[1].column}
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnList = append(yyDollar[1].columnList, yyDollar[3].column)
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = EqualStr
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = NotEqualStr
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = RegexpStr
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotRegexpStr
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GlobStr
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotGlobStr
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = MatchStr
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotMatchStr
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LessThanStr
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GreaterThanStr
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LessEqualStr
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = GreaterEqualStr
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = LikeStr
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotLikeStr
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = BetweenStr
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = NotBetweenStr
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = NoneStr
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = TextStr
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.convertType = IntegerStr
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colTuple = Exprs{}
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colTuple = yyDollar[1].subquery
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.colTuple = yyDollar[2].exprs
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.subquery = &Subquery{Select: yyDollar[2].readStmt}
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &ExistsExpr{Subquery: yyDollar[2].subquery}
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &NotExpr{Expr: &ExistsExpr{Subquery: yyDollar[3].subquery}}
		}
	case 158:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: Identifier("glob"), Args: Exprs{yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 159:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: Identifier("like"), Args: Exprs{yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 160:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: Identifier("like"), Args: Exprs{yyDollar[3].expr, yyDollar[5].expr, yyDollar[7].expr}}
		}
	case 161:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			lowered := strings.ToLower(string(yyDollar[1].identifier))
			if _, ok := AllowedFunctions[lowered]; !ok {
				yylex.(*Lexer).AddError(&ErrNoSuchFunction{FunctionName: string(yyDollar[1].identifier)})
			}
			yyVAL.expr = &FuncExpr{Name: Identifier(lowered), Distinct: yyDollar[3].bool, Args: yyDollar[4].exprs, Filter: yyDollar[6].where}
		}
	case 162:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			lowered := strings.ToLower(string(yyDollar[1].identifier))
			if _, ok := AllowedFunctions[lowered]; !ok {
				yylex.(*Lexer).AddError(&ErrNoSuchFunction{FunctionName: string(yyDollar[1].identifier)})
			}
			yyVAL.expr = &FuncExpr{Name: Identifier(lowered), Distinct: false, Args: nil, Filter: yyDollar[5].where}
		}
	case 163:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = true
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.exprs = Exprs{yyDollar[1].expr}
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 167:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.exprs = nil
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 169:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.where = nil
		}
	case 170:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.where = &Where{Type: WhereStr, Expr: yyDollar[4].expr}
		}
	case 171:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.expr = nil
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 173:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.when = &When{Condition: yyDollar[2].expr, Value: yyDollar[4].expr}
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.whens = []*When{yyDollar[1].when}
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = append(yyDollar[1].whens, yyDollar[2].when)
		}
	case 176:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.expr = nil
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 178:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			if len(yyDollar[5].columnDefList) > MaxAllowedColumns {
				yylex.(*Lexer).AddError(&ErrTooManyColumns{ColumnCount: len(yyDollar[5].columnDefList), MaxAllowed: MaxAllowedColumns})
			}

			// We have to replace a primary key table constraint with an equivalent column constraint primary key,
			// so we can add the autoincrement flag, as part of the rules of the Tableland Protocol.
			//
			// That happens because a primary key table constraint that references a single INTEGER column
			// would be an alias to rowid. For cases where a column becomes an alias to rowid we want to force the AUTOINCREMENT.
			//
			// The exception to the above rule is when a table constraint primary key has order DESC. In that case, we replace with an
			// equivalent column constrain without forcing AUTOINCREMENT and avoiding being interpreted as an alias.
			for index, tableConstraint := range yyDollar[6].tableConstraints {
				if tableConstraintPK, ok := tableConstraint.(*TableConstraintPrimaryKey); ok && len(tableConstraintPK.Columns) == 1 {
					for _, columnDef := range yyDollar[5].columnDefList {
						if columnDef.Type == TypeIntegerStr && !columnDef.HasPrimaryKey() {
							if tableConstraintPK != nil && columnDef.Column.Name == tableConstraintPK.Columns[0].Column.Name {
								forceAutoincrement := tableConstraintPK.Columns[0].Order != PrimaryKeyOrderDesc
								columnDef.Constraints = append(columnDef.Constraints, &ColumnConstraintPrimaryKey{Name: tableConstraintPK.Name, AutoIncrement: forceAutoincrement, Order: tableConstraintPK.Columns[0].Order})
								yyDollar[6].tableConstraints = append(yyDollar[6].tableConstraints[:index], yyDollar[6].tableConstraints[index+1:]...)
							}
						}
					}
				}
			}

			yyVAL.createTableStmt = &CreateTable{Table: yyDollar[3].table, ColumnsDef: yyDollar[5].columnDefList, Constraints: yyDollar[6].tableConstraints}
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnDefList = []*ColumnDef{yyDollar[1].columnDef}
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnDefList = append(yyDollar[1].columnDefList, yyDollar[3].columnDef)
		}
	case 181:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if isRowID(yyDollar[1].column.Name) {
				yylex.(*Lexer).AddError(&ErrRowIDNotAllowed{})
			}

			if yyDollar[2].string == TypeIntegerStr {
				for _, constraint := range yyDollar[3].columnConstraints {
					if primaryKey, ok := constraint.(*ColumnConstraintPrimaryKey); ok {
						if primaryKey.Order != PrimaryKeyOrderDesc {
							primaryKey.AutoIncrement = true
						}
					}
				}
			}
			yyVAL.columnDef = &ColumnDef{Column: yyDollar[1].column, Type: yyDollar[2].string, Constraints: yyDollar[3].columnConstraints}
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = TypeIntStr
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = TypeIntegerStr
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = TypeTextStr
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = TypeBlobStr
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = TypeAnyStr
		}
	case 187:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.columnConstraints = []ColumnConstraint{}
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnConstraints = yyDollar[1].columnConstraints
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if _, ok := yyDollar[1].columnConstraint.(*ColumnConstraintPrimaryKey); ok {
				if yylex.(*Lexer).createStmtHasPrimaryKey {
					yylex.(*Lexer).AddError(&ErrMultiplePrimaryKey{})
				} else {
					yylex.(*Lexer).createStmtHasPrimaryKey = true
				}
			}
			yyVAL.columnConstraints = []ColumnConstraint{yyDollar[1].columnConstraint}
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if _, ok := yyDollar[2].columnConstraint.(*ColumnConstraintPrimaryKey); ok && yylex.(*Lexer).createStmtHasPrimaryKey {
				yylex.(*Lexer).AddError(&ErrMultiplePrimaryKey{})
			}
			yyVAL.columnConstraints = append(yyDollar[1].columnConstraints, yyDollar[2].columnConstraint)
		}
	case 191:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintPrimaryKey{Name: yyDollar[1].identifier, Order: yyDollar[4].string}
		}
	case 192:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintNotNull{Name: yyDollar[1].identifier}
		}
	case 193:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintUnique{Name: yyDollar[1].identifier}
		}
	case 194:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintCheck{Name: yyDollar[1].identifier, Expr: yyDollar[4].expr}
		}
	case 195:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintDefault{Name: yyDollar[1].identifier, Expr: yyDollar[4].expr, Parenthesis: true}
		}
	case 196:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintDefault{Name: yyDollar[1].identifier, Expr: yyDollar[3].expr}
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintDefault{Name: yyDollar[1].identifier, Expr: yyDollar[3].expr}
		}
	case 198:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintGenerated{Name: yyDollar[1].identifier, Expr: yyDollar[6].expr, GeneratedAlways: true, IsStored: yyDollar[8].bool}
		}
	case 199:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.columnConstraint = &ColumnConstraintGenerated{Name: yyDollar[1].identifier, Expr: yyDollar[4].expr, GeneratedAlways: false, IsStored: yyDollar[6].bool}
		}
	case 200:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.identifier = Identifier("")
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.identifier = yyDollar[2].identifier
		}
	case 202:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = PrimaryKeyOrderEmpty
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = PrimaryKeyOrderAsc
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = PrimaryKeyOrderDesc
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].value
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyDollar[2].value.Value = append([]byte("-"), yyDollar[2].value.Value...)
			yyVAL.expr = yyDollar[2].value
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.value = &Value{Type: IntValue, Value: yyDollar[1].bytes}
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*Lexer).AddError(&ErrNumericLiteralFloat{Value: yyDollar[1].bytes})
			yyVAL.value = &Value{Type: FloatValue, Value: yyDollar[1].bytes}
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.value = &Value{Type: HexNumValue, Value: yyDollar[1].bytes}
		}
	case 210:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = true
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bool = false
		}
	case 213:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.tableConstraints = []TableConstraint{}
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableConstraints = yyDollar[1].tableConstraints
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if _, ok := yyDollar[2].tableConstraint.(*TableConstraintPrimaryKey); ok {
				if yylex.(*Lexer).createStmtHasPrimaryKey {
					yylex.(*Lexer).AddError(&ErrMultiplePrimaryKey{})
				} else {
					yylex.(*Lexer).createStmtHasPrimaryKey = true
				}
			}
			yyVAL.tableConstraints = []TableConstraint{yyDollar[2].tableConstraint}
		}
	case 216:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if _, ok := yyDollar[3].tableConstraint.(*TableConstraintPrimaryKey); ok && yylex.(*Lexer).createStmtHasPrimaryKey {
				yylex.(*Lexer).AddError(&ErrMultiplePrimaryKey{})
			}
			yyVAL.tableConstraints = append(yyDollar[1].tableConstraints, yyDollar[3].tableConstraint)
		}
	case 217:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.tableConstraint = &TableConstraintPrimaryKey{Name: yyDollar[1].identifier, Columns: yyDollar[5].indexedColumnList}
		}
	case 218:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.tableConstraint = &TableConstraintUnique{Name: yyDollar[1].identifier, Columns: yyDollar[4].columnList}
		}
	case 219:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.tableConstraint = &TableConstraintCheck{Name: yyDollar[1].identifier, Expr: yyDollar[4].expr}
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.indexedColumnList = IndexedColumnList{yyDollar[1].indexedColumn}
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.indexedColumnList = append(yyDollar[1].indexedColumnList, yyDollar[3].indexedColumn)
		}
	case 222:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.indexedColumn = &IndexedColumn{Column: yyDollar[1].column, CollationName: yyDollar[2].identifier, Order: yyDollar[3].string}
		}
	case 223:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.identifier = Identifier("")
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.identifier = Identifier(string(yyDollar[2].identifier))
		}
	case 225:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			for i := 0; i < len(yyDollar[4].columnList); i++ {
				if isRowID(yyDollar[4].columnList[i].Name) {
					yylex.(*Lexer).AddError(&ErrRowIDNotAllowed{})
				}
			}

			for _, row := range yyDollar[6].insertRows {
				for _, expr := range row {
					if containsSubquery(expr) {
						yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "insert"})
					}
				}
			}
			yyVAL.insertStmt = &Insert{Table: yyDollar[3].table, Columns: yyDollar[4].columnList, Rows: yyDollar[6].insertRows, Upsert: yyDollar[7].upsertClause}
		}
	case 226:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.insertStmt = &Insert{Table: yyDollar[3].table, Columns: ColumnList{}, Rows: []Exprs{}, DefaultValues: true}
		}
	case 227:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.columnList = ColumnList{}
		}
	case 228:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.columnList = yyDollar[2].columnList
		}
	case 229:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.insertRows = []Exprs{yyDollar[2].exprs}
		}
	case 230:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.insertRows = append(yyDollar[1].insertRows, yyDollar[4].exprs)
		}
	case 231:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.upsertClause = nil
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			allConflictClausesExceptLast := yyDollar[1].onConflictClauseList[0 : len(yyDollar[1].onConflictClauseList)-1]
			for _, clause := range allConflictClausesExceptLast {
				if clause.Target == nil {
					yylex.(*Lexer).AddError(&ErrUpsertMissingTarget{})
				}
			}
			yyVAL.upsertClause = yyDollar[1].onConflictClauseList
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.onConflictClauseList = []*OnConflictClause{yyDollar[1].onConflictClause}
		}
	case 234:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.onConflictClauseList = append(yyDollar[1].onConflictClauseList, yyDollar[2].onConflictClause)
		}
	case 235:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.onConflictClause = &OnConflictClause{
				Target: yyDollar[3].onConflictTarget,
			}
		}
	case 236:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			if yyDollar[8].where != nil && containsSubquery(yyDollar[8].where) {
				yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "where"})
			}

			yyVAL.onConflictClause = &OnConflictClause{
				Target: yyDollar[3].onConflictTarget,
				DoUpdate: &OnConflictUpdate{
					Exprs: yyDollar[7].updateList,
					Where: yyDollar[8].where,
				},
			}
		}
	case 237:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.onConflictTarget = nil
		}
	case 238:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].where != nil && containsSubquery(yyDollar[4].where) {
				yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "where"})
			}

			yyVAL.onConflictTarget = &OnConflictTarget{
				Columns: yyDollar[2].columnList,
				Where:   yyDollar[4].where,
			}
		}
	case 239:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDollar[4].where != nil && containsSubquery(yyDollar[4].where) {
				yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "delete"})
			}
			yyVAL.deleteStmt = &Delete{Table: yyDollar[3].table, Where: yyDollar[4].where}
		}
	case 240:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			if yyDollar[5].where != nil && containsSubquery(yyDollar[5].where) {
				yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "where"})
			}
			yyVAL.updateStmt = &Update{Table: yyDollar[2].table, Exprs: yyDollar[4].updateList, Where: yyDollar[5].where}
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.updateList = yyDollar[1].updateList
		}
	case 242:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.updateList = yyDollar[1].updateList
		}
	case 243:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if containsSubquery(yyDollar[1].updateExpression.Expr) {
				yylex.(*Lexer).AddError(&ErrStatementContainsSubquery{StatementKind: "update"})
			}
			yyVAL.updateList = []*UpdateExpr{yyDollar[1].updateExpression}
		}
	case 244:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.updateList = append(yyDollar[1].updateList, yyDollar[3].updateExpression)
		}
	case 245:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			if len(yyDollar[2].columnList) != len(yyDollar[6].exprs) {
				yylex.(*Lexer).AddError(&ErrUpdateColumnsAndValuesDiffer{ColumnsCount: len(yyDollar[2].columnList), ValuesCount: len(yyDollar[6].exprs)})
				yyVAL.updateList = []*UpdateExpr{}
			} else {
				exprs := make([]*UpdateExpr, len(yyDollar[2].columnList))
				for i := 0; i < len(yyDollar[2].columnList); i++ {
					if isRowID(yyDollar[2].columnList[i].Name) {
						yylex.(*Lexer).AddError(&ErrRowIDNotAllowed{})
					}
					exprs[i] = &UpdateExpr{Column: yyDollar[2].columnList[i], Expr: yyDollar[6].exprs[i]}
				}
				yyVAL.updateList = exprs
			}
		}
	case 246:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if isRowID(yyDollar[1].column.Name) {
				yylex.(*Lexer).AddError(&ErrRowIDNotAllowed{})
			}
			yyVAL.updateExpression = &UpdateExpr{Column: yyDollar[1].column, Expr: yyDollar[3].expr}
		}
	case 247:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.grant = &Grant{Table: yyDollar[4].table, Privileges: yyDollar[2].privileges, Roles: yyDollar[6].strings}
		}
	case 248:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.revoke = &Revoke{Table: yyDollar[4].table, Privileges: yyDollar[2].privileges, Roles: yyDollar[6].strings}
		}
	case 249:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strings = []string{string(yyDollar[1].bytes[1 : len(yyDollar[1].bytes)-1])}
		}
	case 250:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, string(yyDollar[3].bytes[1:len(yyDollar[3].bytes)-1]))
		}
	case 251:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			privileges := make(map[string]struct{})
			privileges[yyDollar[1].string] = struct{}{}
			yyVAL.privileges = Privileges(privileges)
		}
	case 252:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if _, ok := yyDollar[1].privileges[yyDollar[3].string]; ok {
				yylex.(*Lexer).AddError(&ErrGrantRepeatedPrivilege{Privilege: yyDollar[3].string})
			}

			yyDollar[1].privileges[yyDollar[3].string] = struct{}{}
			yyVAL.privileges = yyDollar[1].privileges
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = "insert"
		}
	case 254:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = "update"
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = "delete"
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			literalUpper := bytes.ToUpper(yyDollar[1].bytes)
			if _, ok := keywordsNotAllowed[string(literalUpper)]; ok {
				yylex.(*Lexer).AddError(&ErrKeywordIsNotAllowed{Keyword: string(yyDollar[1].bytes)})
			}

			yyVAL.identifier = Identifier(yyDollar[1].bytes)
		}
	}
	goto yystack /* stack new state and value */
}
